spring:
  main:
    web-application-type: none

  application:
    name: ping-worker

  threads:
    virtual:
      enabled: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: guest
    password: guest